#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.8.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend felixfrz.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 452723-web-01 54.157.167.103:80
        server 452723-web-02 52.91.116.35:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart

