#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend felixfrz.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 452723-web-01 52.91.126.106:80
        server 452723-web-02 54.157.174.148:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart

